### ISSUE TITLE
Windows Compatibility on Plugin Repo?

### ISSUE THREAD

**Issue by jneilliii** [om2804/octoprint_mkswifisdcard#1]
Someone on Discord was asking about this plugin in a windows install of OctoPrint and I noticed that the plugin repository's listing was locked to Linux only. I took a quick glance at the code and don't see any reason why this wouldn't work in windows and was wondering if marking it windows compatible on the plugin repository would be ok or not?

**Comment by om2804** [comment]
No problem. But I don't know how to mark Windows is compatible

**Comment by jneilliii** [comment]
No worries, I just removed the OS section for you, which will basically make it compatible to anything that can run OctoPrint.
